### ISSUE TITLE
`formspecs` mod uses `minetest.get_password_hash` to generate a random value.

### ISSUE THREAD

**Issue by red-001** [mt-historical/blockcolor#2]
This is a misuse of the API (see https://github.com/minetest/minetest/issues/12564). 

The call can easily be replaced with `SecureRandom()` with a fall back to `PcgRandom()` if needed.

https://github.com/mt-historical/blockcolor/blob/c9673dea5d9e23f5a0e406bc85c19600362ded63/mods/Other/formspecs/init.lua#L212

**Comment by wsor4035** [comment]
feel free to open a pr
